from __future__ import annotations

from typing import Protocol

from ..models import HoldResult, Offer, Target


class Adapter(Protocol):
    async def warmup(self) -> None: ...
    async def read_cap(self) -> int | None: ...
    async def inventory(self, target: Target) -> list[Offer]: ...
    async def hold(self, target: Target, offer: Offer, qty: int) -> HoldResult: ...
    async def checkout_url(self, hold: HoldResult) -> str: ...
    async def wait_until_admitted(self, target: Target) -> None: ...
    async def aclose(self) -> None: ...
